In [105]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [106]:
# Load the dataset
data = pd.read_csv('/content/drive/MyDrive/Banking Customer Churn Prediction Dataset/Churn_Modelling.csv')  # Replace with your dataset's file path

In [107]:
# Data Preprocessing
# Dropping unnecessary columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [108]:
# Encoding categorical variables
label_encoder_geography = LabelEncoder()
label_encoder_gender = LabelEncoder()

data['Geography'] = label_encoder_geography.fit_transform(data['Geography'])
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [109]:
# Splitting data into features and target
X = data.drop('Exited', axis=1).values
y = data['Exited'].values

In [110]:
# Standardizing the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [111]:
# Preprocessing
def preprocess_data(texts, labels, vocab_size=10000, max_length=100):
    tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
    tokenizer.fit_on_texts(texts)
    sequences = tokenizer.texts_to_sequences(texts)
    padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post', truncating='post')
    return padded_sequences, labels, tokenizer, sequences

In [112]:
# Step 3: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [113]:
# Reshaping data for RNN input (samples, time_steps, features)
X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0], 1, X_test.shape[1]))

In [114]:
X = np.array(range(0,4))
X = X.reshape(1,4)
y=np.array(range(7,8))
y= y.reshape(-1,1)
X,y

(array([[0, 1, 2, 3]]), array([[7]]))

In [115]:
# Preprocessing
def preprocess_data(texts, labels, vocab_size=10000, max_length=100):
    # Flatten the input texts if they are multi-dimensional
    texts = [str(item) for sublist in texts for item in sublist]  # Flatten and convert to strings

    tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
    tokenizer.fit_on_texts(texts)
    sequences = tokenizer.texts_to_sequences(texts)
    padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post', truncating='post')
    return padded_sequences, labels, tokenizer, sequences

In [116]:
vocab

{'<OOV>': 1, '3': 2, '4': 3, '5': 4, '6': 5, '7': 6, '8': 7}

In [117]:

model = Sequential()

In [118]:
# Adding the SimpleRNN layer
model.add(SimpleRNN(units=50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.2))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [119]:
X = np.array(range(0,16))
X = X.reshape(-1,4,4)
y=np.array(range(7,8))
y= y.reshape(-1,1)
X,y

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]]),
 array([[7]]))

In [120]:
# Adding the output layer
model.add(Dense(units=1, activation='sigmoid'))

In [121]:
# Compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [122]:
# Training the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6851 - loss: 0.5894 - val_accuracy: 0.8210 - val_loss: 0.4206
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8107 - loss: 0.4408 - val_accuracy: 0.8290 - val_loss: 0.3990
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8232 - loss: 0.4142 - val_accuracy: 0.8435 - val_loss: 0.3851
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8379 - loss: 0.4000 - val_accuracy: 0.8515 - val_loss: 0.3748
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8454 - loss: 0.3807 - val_accuracy: 0.8575 - val_loss: 0.3652
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8500 - loss: 0.3662 - val_accuracy: 0.8575 - val_loss: 0.3587
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8507 - loss: 0.3655 - val_accuracy: 0.8545 - val_loss: 0.3553
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8461 - loss: 0.3629 - val_accuracy: 0.

In [123]:
# Evaluating the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8587 - loss: 0.3505
Test Loss: 0.3480135202407837
Test Accuracy: 0.859000027179718


In [124]:
# Generating the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[1560   47]
 [ 233  160]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.97      0.92      1607
           1       0.77      0.41      0.53       393

    accuracy                           0.86      2000
   macro avg       0.82      0.69      0.73      2000
weighted avg       0.85      0.86      0.84      2000



In [125]:
# Predicting and visualizing the results
y_pred = (model.predict(X_test) > 0.5).astype(int)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [126]:
X = np.array(range(0,9))
X = X.reshape(3,3)
y=np.array(range(5,8))
y= y.reshape(-1,1)
y.shape, X,y

((3, 1),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[5],
        [6],
        [7]]))

In [127]:
# Experimental Models with Sequential Data
# First Model
X_exp1 = np.array(range(0, 4))
X_exp1 = X_exp1.reshape(1, 4, 1)  # Reshape for (samples, time_steps, features)
y_exp1 = np.array(range(7, 8)).reshape(-1, 1)  # Reshape for (samples, output_dim)

model_exp1 = Sequential()
model_exp1.add(SimpleRNN(1, input_shape=(4, 1), activation='tanh'))
model_exp1.add(Dense(units=1, activation='relu'))
model_exp1.compile(loss='mean_squared_error', optimizer='adam')
model_exp1.fit(X_exp1, y_exp1, epochs=10, verbose=1)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 29.9095
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 29.8870
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 29.8645
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 29.8420
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 29.8196
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 29.7971
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 29.7747
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 29.7523
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 29.7299
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 29.7075


In [128]:
# Second Model
X_exp2 = np.array(range(0, 16))
X_exp2 = X_exp2.reshape(-1, 4, 4)  # Reshape for (samples, time_steps, features)
y_exp2 = np.array(range(7, 8)).reshape(-1, 1)  # Reshape for (samples, output_dim)

model_exp2 = Sequential()
model_exp2.add(SimpleRNN(1, input_shape=(4, 4), activation='tanh'))
model_exp2.add(Dense(units=1, activation='relu'))
model_exp2.compile(loss='mean_squared_error', optimizer='adam')
model_exp2.fit(X_exp2, y_exp2, epochs=10, verbose=1)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 49.0000
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 49.0000
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 49.0000
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 49.0000
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 49.0000
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 49.0000
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 49.0000
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 49.0000
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 49.0000
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 49.0000


In [129]:
# Third Model
X_exp3 = np.array(range(0, 9))
X_exp3 = X_exp3.reshape(3, 3, 1)  # Reshape for (samples, time_steps, features)
y_exp3 = np.array(range(5, 8)).reshape(-1, 1)  # Reshape for (samples, output_dim)

model_exp3 = Sequential()
model_exp3.add(SimpleRNN(1, input_shape=(3, 1), activation='tanh'))
model_exp3.add(Dense(units=1, activation='relu'))
model_exp3.compile(loss='mean_squared_error', optimizer='adam')
model_exp3.fit(X_exp3, y_exp3, epochs=10, verbose=1)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 36.6667
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 36.6667
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 36.6667
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 36.6667
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 36.6667
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 36.6667
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 36.6667
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 36.6667
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 36.6667
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 36.6667


In [132]:
# Get weights and biases of each layer
print("\nWeights and Biases of the Model:")

# Assuming you want weights from model_exp3, replace 'model' with 'model_exp3'
model = model_exp3  # Or model_exp1, model_exp2, depending on your needs

# Get weights and biases of the SimpleRNN layer
rnn_weights = model.layers[0].get_weights()  # Simple RNN Layer
print("\nSimpleRNN Layer Weights and Biases:")
print(f"RNN Weights Shape: {rnn_weights[0].shape}")
print(f"RNN Biases Shape: {rnn_weights[1].shape}")

# Get weights and biases of the output (Dense) layer
dense_weights = model.layers[1].get_weights()  # Output Dense Layer
print("\nDense Layer Weights and Biases:")
print(f"Dense Weights Shape: {dense_weights[0].shape}")
print(f"Dense Biases Shape: {dense_weights[1].shape}")


Weights and Biases of the Model:

SimpleRNN Layer Weights and Biases:
RNN Weights Shape: (1, 1)
RNN Biases Shape: (1, 1)

Dense Layer Weights and Biases:
Dense Weights Shape: (1, 1)
Dense Biases Shape: (1,)
